@startuml
left to right direction
skinparam roundcorner 5
skinparam shadowing false

skinparam class {
    BackgroundColor white
    ArrowColor #2688d4
    BorderColor #2688d4
}

!define primary_key(x) <b><color:#b8861b><&key></color> x</b>
!define foreign_key(x) <color:#aaaaaa><&key></color> x
!define column(x) <color:#efefef><&media-record></color> x
!define table(x) entity x << (T, white) >>

table(address) {
    primary_key(id): UUID
    --
    column(country): VARCHAR(127)
    column(city): VARCHAR(127)
    column(street): VARCHAR(255)
    column(postcode): VARCHAR(16)
}

table(subscription) {
    primary_key(id): UUID
    --
    column(name): VARCHAR(255)
    column(price): DECIMAL
    column(type): VARCHAR(64)
    column(period): ENUM
}

table(user) {
    primary_key(id): UUID
    --
    ' user info
    column(email): VARCHAR(255)
    column(first_name): VARCHAR(127)
    column(last_name): VARCHAR(127)
    column(phone_number): VARCHAR(16)
    column(password_hash): BINARY(64)
    ' subscription info
    column(subscription_expiration_date): DATE
    column(created_at): DATETIME
    column(updated_at): DATETIME
    foreign_key(subscription_id): UUID
}

user::subscription_id --> subscription::id

table(tag) {
    primary_key(id): UUID
    --
    column(name): VARCHAR(32)
}

table(item) {
    primary_key(id): UUID
    --
    column(name): VARCHAR(32)
    column(description): TEXT
    column(price): DECIMAL
    column(state): ENUM
    column(created_at): DATETIME
    column(updated_at): DATETIME
    foreign_key(user_id): UUID
}

' TODO: item keywords?

item::user_id --> user::id

table(item_tag) {
    primary_key(id): UUID
    --
    foreign_key(item_id): UUID
    foreign_key(tag_id): UUID
}

item_tag::item_id --> item::id
item_tag::tag_id --> tag::id

table(item_image) {
    primary_key(id): UUID
    --
    column(content): BLOB
    foreign_key(item_id): UUID
}

item_image::item_id --> item::id

table(favorite_item) {
    primary_key(id): UUID
    --
    foreign_key(item_id): UUID
    foreign_key(user_id): UUID
}

favorite_item::item_id --> item::id
favorite_item::user_id --> user::id

@enduml
