@startuml

scale 3
skinparam activity {
    BackgroundColor white
    ArrowColor #2688d4
    BorderColor #2688d4
}

start
switch (Выбор состояния товара)
case (Товар доступен к покупке?)
    :Товар становится виден остальным пользователям;
case (Товара нет в наличии?)
    :Товар остается виден остальным пользователям;
case (Товар убран из продажи?)
    :Товар помечается как проданный;
endswitch
:Изменение состояния товара;
end

@enduml
