@startuml

scale 3
skinparam activity {
    BackgroundColor white
    ArrowColor #2688d4
    BorderColor #2688d4
}

start
:Вход в аккаунт;
if (Пользователь зарегистрирован?) then (Да)
    :Переход на страницу входа;
else (Нет)
    :Переход на страницу регистрации;
endif
end

@enduml
