@startuml

scale 3
skinparam activity {
    BackgroundColor white
    ArrowColor #2688d4
    BorderColor #2688d4
}

start
:Ввод запроса и/или тегов;
switch (Какой тип поиска?)
case (Только теги?)
    :Поиск по тегам;
case (Только запрос?)
    :Поиск по запросу;
case (Теги и запрос?)
    :Поиск по тегам и запросу;
endswitch
:Выдача результатов;
end

@enduml
