@startuml

scale 3
skinparam activity {
    BackgroundColor white
    ArrowColor #2688d4
    BorderColor #2688d4
}

start
:Ввод поискового запроса и/или тегов;
switch (Какой тип поиска?)
case (Добавлены только теги)
    :Поиск только по тегам;
case (Добавлен только поисковый запрос?)
    :Поиск только по поисковому запрос;
case (Добавлены и теги, и поисковый запрос?)
    :Поиск и по тегами, и по поисковому запросу;
endswitch
:Выдача результатов поискового запроса;
end

@enduml
