@startuml

scale 3
skinparam activity {
    BackgroundColor white
    ArrowColor #2688d4
    BorderColor #2688d4
}

start
:Выбор продавца;
:Переход на страницу отзывов;
:Просмотр отзывов;
:Добавление отзыва;
if (Пользователь вошел в аккаунт?) then (Да)
    :Создание отзыва;
    :Публикация отзыва;
    if (Модерация пройдена?) then (Да)
        :Отзыв остается виден пользователям;
    else (Нет)
        :Отзыв скрывается от пользователей;
    endif
else (Нет)
    :Переход на страницу входа;
    end
endif
end

@enduml
